name: hello-world
on: workflow_dispatch
jobs:
  first:
    env:
       uname: ${{secrets.user_name}}
       upass: ${{secrets.user_pass}}
     runs-on: self-hosted 
     steps:
      - name: install apache2 server 
        run: sudo apt install apache2 -y
  second:
     needs: first
     runs-on: self-hosted
     steps:
      - name: install nginxi apache server 
        run: sudo apt install nginx -y
      - name: information 
        run: | 
           echo: "uname" ${{ env.uname }}
           echo: "upass" ${{ env.upass }}
      