name: hello-world
on: push 
jobs:
  first:
     runs-on: self-hosted 
     steps:
      - name: install apache2 server 
        run:  apt install apache2 -y
  second:
     runs-on: self-hosted
     steps:
      - name: install nginx
        run:  apt install nginx -y 
    
