name: hello-world
on: workflow_dispatch
jobs:
  first:
     runs-on: self-hosted 
     steps:
      - name: install apache2 server 
        run: sudo apt install apache2 -y
  second:
     needs: first
     runs-on: self-hosted
     steps:
      - name: install nginxi apache server 
        run: sudo apt install nginx -y 
