name: hello-world
on: push 
jobs:
  first:
     runs-on: self-hosted 
     steps:
      - name: uinstall apache server
        run: yum remove apahe2 -y
      - name: completetly uninstall apache2 server
        run: yum erase httpd httpd-tools apr apr-util
