name: hello-world
on: push
jobs:
  my-job:
    runs-on: self-hosted
    steps:
      - name: my-step
        run: echo "Hello World!"
      - name: create file
        run: touch a{1..100}.txt
      - name: create folder 
        run: mkdir hello-action
