name: hello-world
on: push 
jobs:
  first:
     runs-on: self-hosted 
     steps:
      - name: install apache2 server 
        run:  apt install apache2 -y 
      - name: completetly uninstall apache2 server
        run: apr remove apache2 -y
        run:  sudo apt autoremove -y
  second:
     runs-on: self-hosted:
     steps:
        - name: install nginx server 
          run: apt install nginx -y  
