name: hello-world
on: push 
jobs:
  first:
     runs-on: self-hosted 
     steps:
      - name: install apache2 server 
        run: sudo apuut install apache2 -y
  second:
     needs: first
     runs-on: self-hosted
     steps:
      - name: install nginx
        run: sudo apt install nginx -y 
